//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selenium.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnvtestOR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnvtestOR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Selenium.Properties.EnvtestOR", typeof(EnvtestOR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //b[contains(.,&apos;Airtime&apos;)].
        /// </summary>
        internal static string Airtime {
            get {
                return ResourceManager.GetString("Airtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //b[contains(@translate,&apos;.bill-so-far._&apos;)].
        /// </summary>
        internal static string Billsofar {
            get {
                return ResourceManager.GetString("Billsofar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;txtCellNumber&apos;].
        /// </summary>
        internal static string CellphoneNumbertxtBox {
            get {
                return ResourceManager.GetString("CellphoneNumbertxtBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;txtEmailConfirm&apos;].
        /// </summary>
        internal static string ConfirmEmailtxtBox {
            get {
                return ResourceManager.GetString("ConfirmEmailtxtBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;ssoPasswordConfirm&apos;].
        /// </summary>
        internal static string ConfirmPasswordTxtBox {
            get {
                return ResourceManager.GetString("ConfirmPasswordTxtBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;ssoPassword&apos;].
        /// </summary>
        internal static string CreatePasswordTxtBox {
            get {
                return ResourceManager.GetString("CreatePasswordTxtBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;txtEmail&apos;].
        /// </summary>
        internal static string EmailAdresstxtBox {
            get {
                return ResourceManager.GetString("EmailAdresstxtBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;firstName&apos;].
        /// </summary>
        internal static string FirstNameTxtBox {
            get {
                return ResourceManager.GetString("FirstNameTxtBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;idPassNumber&apos;].
        /// </summary>
        internal static string ID_PassporttxtTxtBox {
            get {
                return ResourceManager.GetString("ID_PassporttxtTxtBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(.,&apos;Log in&apos;)].
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@class=&apos;btn btnPurple login-password&apos;].
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(.,&apos;Log out&apos;)].
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(.,&apos;Manage my account&apos;)].
        /// </summary>
        internal static string ManageMyAccount {
            get {
                return ResourceManager.GetString("ManageMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@type=&apos;password&apos;].
        /// </summary>
        internal static string PasswordInput {
            get {
                return ResourceManager.GetString("PasswordInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@value=&apos;1&apos;].
        /// </summary>
        internal static string RadioBtn1 {
            get {
                return ResourceManager.GetString("RadioBtn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@value=&apos;2&apos;].
        /// </summary>
        internal static string RadioBtn2 {
            get {
                return ResourceManager.GetString("RadioBtn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(.,&apos;Register&apos;)].
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;search&apos;].
        /// </summary>
        internal static string Searchbar {
            get {
                return ResourceManager.GetString("Searchbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(.,&apos;Search&apos;)].
        /// </summary>
        internal static string SearchIcon {
            get {
                return ResourceManager.GetString("SearchIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(.,&apos;Set a reminder&apos;)].
        /// </summary>
        internal static string SetReminder {
            get {
                return ResourceManager.GetString("SetReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[contains(.,&apos;Upgrade now&apos;)].
        /// </summary>
        internal static string UpgradeNow {
            get {
                return ResourceManager.GetString("UpgradeNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@id=&apos;username&apos;].
        /// </summary>
        internal static string UsernameInput {
            get {
                return ResourceManager.GetString("UsernameInput", resourceCulture);
            }
        }
    }
}
