//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selenium.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Selenium.Properties.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;T325213152811425995191839portangulargenmenu&quot;]/span/nav/ul/li[4]/span/span/ul/li[4]/span/a.
        /// </summary>
        internal static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;confirmDeregisterNumber&quot;].
        /// </summary>
        internal static string DeactivateBtn {
            get {
                return ResourceManager.GetString("DeactivateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;submitDeregisterNumber&quot;].
        /// </summary>
        internal static string DeactivateBtn2 {
            get {
                return ResourceManager.GetString("DeactivateBtn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;manageUsersDeregisterSuccess&quot;]/div/div/p.
        /// </summary>
        internal static string DeregisterSuccess {
            get {
                return ResourceManager.GetString("DeregisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;row_1517494309-2000102415358-bbdtester&quot;]/div/div[4].
        /// </summary>
        internal static string EmailInbox {
            get {
                return ResourceManager.GetString("EmailInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[contains(.,&apos;Email does not match.&apos;)].
        /// </summary>
        internal static string EmailNotmatch {
            get {
                return ResourceManager.GetString("EmailNotmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[@ng-show=&apos;ctrl.registrationForm.txtCellNumber.$error.required &amp;&amp; temp.submitted&apos;].
        /// </summary>
        internal static string FieldReq {
            get {
                return ResourceManager.GetString("FieldReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[contains(.,&apos;Please enter no more than 13 characters.&apos;)].
        /// </summary>
        internal static string ID_PassMorethn13 {
            get {
                return ResourceManager.GetString("ID_PassMorethn13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[@ng-show=&apos;temp.validation.idInvalid&apos;].
        /// </summary>
        internal static string ID_PassortMsg {
            get {
                return ResourceManager.GetString("ID_PassortMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/table[2]/tbody/tr[1]/td/table/tbody/tr/td/p[2]/a.
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;portangularactivateregistration&quot;]/div[2]/section/div/div/div[2]/a.
        /// </summary>
        internal static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[contains(.,&apos;You have successfully logged out.&apos;)].
        /// </summary>
        internal static string LogoutMsg {
            get {
                return ResourceManager.GetString("LogoutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/section[1]/div/div[3]/div[2]/div[2]/div[1]/span/button.
        /// </summary>
        internal static string MailGoBtn {
            get {
                return ResourceManager.GetString("MailGoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;inboxfield&quot;].
        /// </summary>
        internal static string MailTxtbox {
            get {
                return ResourceManager.GetString("MailTxtbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //label[contains(.,&apos;Password does not match.&apos;)].
        /// </summary>
        internal static string PasswordNotMarch {
            get {
                return ResourceManager.GetString("PasswordNotMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;T325213152811425995191839portangulargenmenu&quot;]/span/nav/ul/li[4]/span/span/a/span[1].
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/table[2]/tbody/tr[1]/td/table/tbody/tr/td/p[2]/a.
        /// </summary>
        internal static string VerifyRegistration {
            get {
                return ResourceManager.GetString("VerifyRegistration", resourceCulture);
            }
        }
    }
}
